sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis ## && travis login && travis token
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
# travis encrypt 'GIT_NAME="wAOndering" GIT_EMAIL="tvaissie@scripps.edu" GH_TOKEN=p6x0omduNQqyR5JD3Qzf7w'

env:
  global:
    secure: "HY02ypucO6suv23nyuKcTlFHfvQA3Det++VzcQ7yCs5Rz9kJkaPhUBqsFze3JBXgQKClDIY7DTS3ci/ZXH94VujDr31JO3DmIQBJMRSRE5V8jnzq4kWEhmYA7adKgtThvCtoV0SgQjA8el3XOiW0h9UU1BUXYlVMWg85Yl22JB4TCrGzoDIeaUintxxsFiKaaK3Gul1lUgJ/ZIV/BCTj6IibnA5igu/Slao1m2bvnwydirYHjNYxeuTSH94jOLVfcc/IS5ReRCt4yJHdgS5XMmVOyHN5BzJnWhMW+vsPqNNLmKUcdCtQMAQ/3fu6W5Dhe+YDOl+O8U1ZliBTDeFImmVE+z9+UBtRE8vfVKJpaJ0xY3pj6LQHrdR5Xso8ykOLxThgpPM/I3gbt+Eg5bbYZn9nNXfEjGvkD93FNWOZw7r7EsnL9k1vAGXvWhbGCKtVkudyz0uVgrMO+JAovTdn5OoGH1hAKZm8MMNz/gbvtKBOaJ1PpT9uDI/sM/wAJkJeYy8FAl9OgxfHBCoABrJmmtUJw4nLbqIPpfK3m0In1PqYtbLCxbC263LprcvuEsbxQMbv1jc6xzmjvGntF/vFiD1OehZ1GcnNmC01rCdCBcraFPZ0ZA/kARxCyeB7uoipSCn/THf2LpuWr8tujb9KLnBEQH+10eWugat7JI5V8jw="
branches:
  only:
    - master
